### ISSUE TITLE
[blog] "Zero to `esc run <env> aws s3 ls`"

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/docs#10058]
## Details

It should briefly cover:
1. configuring an OIDC provider
2. the companion environment definition
3. running commands

Note: Add K8s once supported

## Resources

- [ESC 1k Users Plan](https://docs.google.com/spreadsheets/d/1i9_cmTFtkEYLiTQwMyXNChud_2sl-Ca8sngymHLsKdE/edit#gid=0)
- [Draft PR](https://github.com/pulumi/pulumi-hugo/pull/3554)

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/10107
- [ ] https://github.com/pulumi/docs/issues/10125
- [ ] https://github.com/pulumi/docs/issues/10126
- [ ] https://github.com/pulumi/docs/issues/10204
- [ ] https://github.com/pulumi/docs/issues/10193
```

**Comment by aaronkao** [comment]
Ad copy

`aws s3 ls` without `InvalidAccessKey`

**Comment by arunkumar611** [comment]
updated the list of providers

**Comment by toriancrane** [comment]
Feedback from Slack: One thing to call out.  Luke wanted us to have all of the individual cloud provider zero to esc run guides in the docs section similar to how we have for Pulumi IaC. We'd want 1 single blog post showing one scenario and have a call to action that points the user to checkout the docs for more scenarios. We do not want to have 7 separate blogs for each provider!"



![Image](https://github.com/pulumi/docs/assets/19211559/718a8bb0-ee2c-4c7c-a571-6e1693b0cc23)

**Comment by toriancrane** [comment]
We are now pivoting this project to focus on creating step by step docs for OIDC configuration between Pulumi and relevant providers, similar to how it is done on [this site](https://docs.env0.com/docs/oidc-with-aws).

The goal now is to bring our [current OIDC documentation](https://www.pulumi.com/docs/pulumi-cloud/deployments/oidc/) up one level so that it does not live underneath deployments and to update them so that they accommodate for multiple services.

Removing the focus on dynamic credentials for CLI commands unblocks me from the Azure and GCP tasks.

**Comment by toriancrane** [comment]
Draft PR available for updating/reorganizing our existing OIDC content so that it accommodates for more than one service (right now it is very Deployments flavored).

At the moment, I have done the following:

- Move OIDC content from under Deployments to Pulumi Cloud
- Updated OIDC hub page content
- Updated Azure OIDC page content

Posted in `#team-docs` channel for early round of reviews.

**Comment by toriancrane** [comment]
Latest update:

- prioritize AWS OIDC content page including existing gifs/images from blog
- Azure and GCP will be text for now
- update ESC providers page to direct users to OIDC page

Next week will be dedicated towards figuring out how to do OIDC(?) with Vault
