### ISSUE TITLE
Create Review Stacks tutorial

### ISSUE THREAD

**Issue by interurban** [pulumi/docs#10287]
Adding this topic to our backlog of tutorials

```[tasklist]
### Tasks
- [ ] Identify expected audience
- [ ] Identify learning objectives
- [ ] Define the problem statement
- [ ] Proper title and difficulty level identified
- [ ] Developed an outline
- [ ] Identify CTA/Next steps
- [ ] Draft the tutorial
```
