### ISSUE TITLE
[Epic] Pulumi Deployments content

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10296]
- [ ] https://github.com/pulumi/docs/issues/10305
- [ ] https://github.com/pulumi/docs/issues/10304
- [ ] https://github.com/pulumi/docs/issues/10297
- [ ] https://github.com/pulumi/docs/issues/10286
- [ ] https://github.com/pulumi/docs/issues/10287
- [ ] https://github.com/pulumi/docs/issues/10285

**Comment by jkodroff** [comment]
@thoward I think we can close this and leave the individual issues open.
