### ISSUE TITLE
Transferred Issue Tracker

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10302]
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/1507
- [ ] https://github.com/pulumi/pulumi/issues/14555
- [ ] https://github.com/pulumi/pulumi/issues/14463
- [x] https://github.com/pulumi/pulumi-vsphere/issues/350
- [ ] https://github.com/pulumi/docs/issues/3473
- [ ] https://github.com/pulumi/pulumi/issues/14703
- [ ] https://github.com/pulumi/pulumi-dotnet/issues/851
- [x] https://github.com/pulumi/pulumi/issues/14845
- [ ] https://github.com/pulumi/pulumi/issues/14869
- [x] https://github.com/pulumi/pulumi-kubernetes/issues/2837
