### ISSUE TITLE
Single "Getting Started" tutorial

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1033]
Changes currently live at https://hugo.pulumi.io (repurposed dev stack)

## Tasks

- [x] [Fix code snippet scroll behavior](https://github.com/pulumi/docs/pull/1149)
- [x] [Single place to update the latest-version](https://github.com/pulumi/docs/pull/1152)
- [x] [Fix hover for primary buttons](https://github.com/pulumi/docs/pull/1154)
- [ ] Pull Request #1169
- [ ] Language tab choice doesn’t persist across pages or sessions [PR: #1161]

## Follow-ups and Next Steps

- [ ] We have various abbreviated “Get Started” flows throughout the docs (e.g. before each tutorial). Do a pass throughout the entire doc content and ensure we’re consistent about installing Pulumi, prerequisites, configuring providers, etc., and recommending the overall Get Started guides as the single place to get started with Pulumi before anything else.
- [ ] Inline streamlined “configuring” steps for each of the clouds instead of only linking to the more detailed pages
- [ ] Introduce a “Manage the Stack” step before “Destroy the Stack” which talks about interacting with the stack in the Pulumi Console and benefits (showing history of updates, logs, listing of resources, cloud console links, etc.).
- [ ] Instead of showing CLI output as code snippets, use screenshots or animated gifs to make it more visually interesting
- [ ] Use the updated cloud branding images throughout the docs
- [ ] Intros and Summaries: Provide nicer intros at the start of each cloud's guide (e.g. inline some of the "Why Pulumi?" content for Kubernetes), and nicer summaries in the concluding "Next Steps" pages, including links to API docs, GitHub repos, and links to "Architecture & Concepts"
- [ ] P2: Link to API docs throughout the Get Started guides, when referring to particular APIs used in code snippets (S3 bucket, etc.)
- [ ] Open issue on what we want to do with the content in `/quickstart/cloudfx`
- [ ] Open issue on what we want to do with the content in `/quickstart/k8s-the-prod-way`

## Original Description

From Joe:

> We have two *very different* onboarding flows.
>
> Upon reflection, I believe it's actually less about "CLI vs Service", and more about these two different approaches.
>  1. One approach is to create a new project
>  2. Another approach is to walk through a tutorial
>
> I am increasingly believing for first timers, we should have _one tutorial_, no decisions to make.
>
> Having someone create a blank project is ... daunting ... for the same reason it's hard to start anything from scratch.
>
> It's true that the templates have scaffolding, and nudge you to `pulumi up` them, but it feels very different.

Let's create a single tutorial for new users, and encourage its use as the primary "Getting Started" CTA on the homepage (replacing the current 3 CTAs: INSTALL, GET STARTED, LEARN). Users pick their cloud and language and the tutorial walks through the same equivalent program, from the command to get the CLI to deploying the program. Perhaps something along the lines of https://github.com/pulumi/templates/tree/master/hello-aws-javascript, converted into something that makes sense for all clouds.

Consider reconciling with the Tour (which we no longer link to directly).

Related: #997

**Comment by justinvp** [comment]
Given its importance and that there's still remaining work to do to land a really great experience, I'm going to move this into M24, with the goal to complete the majority of the remaining work this week. I've added a list of tasks that I'll be landing incrementally into a feature branch, which I'll deploy to https://hugo.pulumi.io (existing dev stack that I'll repurpose) so folks can more easily review.

**Comment by justinvp** [comment]
Update: I have a set of changes that's in a good enough state to start landing (currently deployed at https://hugo.pulumi.io). Going to start opening smallish PRs against a feature branch. I've updated the issue with the list of remaining work items that we can iterate on subsequently.
