### ISSUE TITLE
[Epic] Pulumi ESC content enhancements

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10356]
Feedback received by Arun:

- Docs were their biggest feedback. Quote "There are two pages with a lot of content. Really hard to discover what's possible, and isn't easily consumable"
- They didn't realize ESC could store secrets, and they were planning on storing them in GCP and retrieving them during runtime. Once I showed them, they just wanted to store within ESC and not have to work with multiple systems

## Resources

- [ESC Content Organization Proposal](https://docs.google.com/document/d/1UvKJTIpcCInzwwsoRNEh5n-nqxk8D7LYUePfQvo4rWg/edit#heading=h.jophudfxf644)
- [Github branch](https://github.com/pulumi/pulumi-hugo/tree/torian/esc-updates)

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/10375
- [ ] https://github.com/pulumi/docs/issues/10602
- [ ] https://github.com/pulumi/docs/issues/10376
- [ ] https://github.com/pulumi/docs/issues/10377
- [ ] https://github.com/pulumi/docs/issues/10378
- [ ] https://github.com/pulumi/docs/issues/10382
- [ ] https://github.com/pulumi/docs/issues/10379
- [ ] https://github.com/pulumi/docs/issues/10381
- [ ] https://github.com/pulumi/docs/issues/10392
- [ ] https://github.com/pulumi/docs/issues/10383
- [ ] https://github.com/pulumi/docs/issues/10384
- [ ] https://github.com/pulumi/docs/issues/10385
- [ ] https://github.com/pulumi/docs/issues/10386
- [ ] https://github.com/pulumi/docs/issues/11548
- [ ] https://github.com/pulumi/docs/issues/10380
- [ ] https://github.com/pulumi/docs/issues/10568
```

**Comment by jkodroff** [comment]
The referenced materials are old and out of date at this point. Closing.
