### ISSUE TITLE
Add "retrieve secrets from external resources" page

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10392]
- AWS
- Azure
- GCP
- Vault (to be added later)
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/10565
- [ ] https://github.com/pulumi/docs/issues/10566
- [ ] https://github.com/pulumi/docs/issues/10567
```

Break into tasklist items per provider content
