### ISSUE TITLE
[Epic] Inputs/Outputs Content Enhancement

### ISSUE THREAD

**Issue by toriancrane** [pulumi/docs#10553]
## Resources

- [Content Enhancement Recommendations](https://docs.google.com/document/d/1r4ik9rdP_Al3pDXCk8UTh_ppMPrbTue7HD1MYe9IV28/edit?usp=sharing)
- [Inputs/Outputs Doc](https://www.pulumi.com/docs/concepts/inputs-outputs/)
- [Inputs and Outputs Youtube](https://www.youtube.com/watch?v=lybOxul2otM)
- [Draft PR](https://github.com/pulumi/pulumi-hugo/pull/3915)

- [ ] https://github.com/pulumi/docs/issues/10554
- [ ] https://github.com/pulumi/docs/issues/10762
- [ ] https://github.com/pulumi/docs/issues/10555
- [ ] https://github.com/pulumi/docs/issues/10556
- [ ] https://github.com/pulumi/docs/issues/10559
- [ ] https://github.com/pulumi/docs/issues/10800
- [ ] https://github.com/pulumi/docs/issues/11013
- [ ] https://github.com/pulumi/docs/issues/10801
- [ ] https://github.com/pulumi/docs/issues/10782
- [ ] https://github.com/pulumi/docs/issues/10564
- [ ] https://github.com/pulumi/docs/issues/10563
- [ ] https://github.com/pulumi/docs/issues/10562
- [ ] https://github.com/pulumi/docs/issues/10560
- [ ] https://github.com/pulumi/docs/issues/10561
- [ ] https://github.com/pulumi/docs/issues/10557
- [ ] https://github.com/pulumi/docs/issues/10823

**Comment by jkodroff** [comment]
The draft PR was merged, so assuming that this work was completed.
