### ISSUE TITLE
[Project] Readme standardization

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#10577]
Update all public GitHub repos' README with more information and community benefits.
```[tasklist]
### Tasks
- [x] Identify list of public repos
- [x] Sort by number of stars
- [x] Develop a checklist
- [x] Develop a template
- [ ] Approve Template
- [ ] Create PRs with the template
```

[Link to the Internal Google Drive Folder](https://drive.google.com/drive/folders/1ETD-sreIH2IEAQ-9SlkBXvzvOZzurXQe)

**Comment by interurban** [comment]
Closing this one as a duplicate for the source issue: https://github.com/pulumi/marketing/issues/986
