### ISSUE TITLE
Improve secrets concept pages

### ISSUE THREAD

**Issue by interurban** [pulumi/docs#11228]
Quality and clarity improvements to https://www.pulumi.com/docs/concepts/secrets/

## Resources

- [Concept review document](https://docs.google.com/document/d/1KbEi3JwsB8XOvhQRkRenZMk1kI5WKQXrJoe_SQ_gw-4/edit?usp=sharing)

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/11276
- [ ] https://github.com/pulumi/docs/issues/11277
- [ ] https://github.com/pulumi/docs/issues/11320
```
