### ISSUE TITLE
[Epic] Create new Content Library

### ISSUE THREAD

**Issue by shughes26** [pulumi/docs#11477]
Create the Content Library page as a centralized location for the following content types:
- Articles
- Case Studies
- AI Answers
- Videos
- Whitepapers

[Link to Figma](https://www.figma.com/file/D8Cr4pYCZ73LqTOxUH2NIP/events?type=design&node-id=0%3A1&mode=dev&t=pEZZykn1JUeg3Q73-1)

```[tasklist]
### Tasks
- [ ] determine content collections
- [ ] create list page
- [ ] reformat case studies
- [ ] create headers for existing case studies
- [ ] create article page format
- [ ] create video page format
- [ ] create AI answers page format
```
