### ISSUE TITLE
Update AWSx EKS Guides

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#11535]
```[tasklist]
### Tasks
- [x] Update examples to use the new program shortcode
- [x] Include examples for missing languages (mostly JavaScript)
- [x] Update the makrdown to adhere to our style guide, added clarity, and links where relevant
- [x] Updated pre-reqs list
```

**Comment by cnunciato** [comment]
Assigning myself here to review the state of this work and determine what's left to bring it over the line.
