### ISSUE TITLE
[Epic] Update AWS guide(s) to use full Pulumi programs

### ISSUE THREAD

**Issue by desteves** [pulumi/docs#11543]
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/docs/issues/11535
- [ ] https://github.com/pulumi/pulumi-hugo/issues/3767
- [ ] Update AWS IAM Guides
- [ ] Update AWS CloudWatch Guides
- [ ] Update AWS Auto Scaling Guides
```

**Comment by jkodroff** [comment]
The items on this epic that have issues are completed. Closing fixed.
