### ISSUE TITLE
[Epic] Add all supported languages to AWS guides

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#11614]
this feedback came in through docs feedback..
>This page lists everything in C++. I am not using C++. I am using Python.

on this page https://www.pulumi.com/docs/clouds/aws/aws-guides/ec2/
im guessing this feedback is related to these pages not having language selectors

i really believe we should remove these very old pages and redirect to the new aws cloud pages

these are the old pages...

- [ ] https://github.com/pulumi/docs/issues/11491
- [ ] https://github.com/pulumi/docs/issues/11490
- [ ] https://github.com/pulumi/docs/issues/11489
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/athena/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/cloudwatch/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/dynamodb/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/ecr/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/kinesis/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/sns/
- [ ] https://www.pulumi.com/docs/clouds/aws/aws-guides/sqs/
