### ISSUE TITLE
Get Started follow-ups

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1173]
- [x] (bermudezmt) We have various abbreviated “Get Started” flows throughout the docs (e.g. before each tutorial). Do a pass throughout the entire doc content and ensure we’re consistent about installing Pulumi, prerequisites, configuring providers, etc., and recommending the overall Get Started guides as the single place to get started with Pulumi before anything else.
- [ ] (bermudezmt) Inline streamlined “configuring” steps for each of the clouds instead of only linking to the more detailed pages
- [x] (justinvp) Update the Azure examples to not flow the location, as that's no longer required (Moved to its own issue #1535)
- [ ] (bermudezmt & cnunciato) Intros and Summaries: Provide nicer intros at the start of each cloud's guide (e.g. inline some of the "Why Pulumi?" content for Kubernetes), and nicer summaries in the concluding "Next Steps" pages, including links to API docs, GitHub repos, and links to "Architecture & Concepts". Note from Justin: For Kubernetes in particular, Mike suggested taking the first section of https://www.pulumi.com/docs/reference/clouds/kubernetes/ (intro, diagram, and bullet points) and put that in the Get Started guide for Kubernetes.
- [ ] (bermudezmt & cnunciato) Add overview diagrams in appropriate places, e.g. on the new /docs home page and in /docs/reference. Note from Justin: I removed a couple diagrams that Mike had created/added, as they didn't fit with the new Get Started guide, but we wanted to bring them back in some form, either somewhere on the /docs landing page itself, or in the "Learning Pulumi" selection in /docs/reference. [These](https://github.com/pulumi/docs/pull/1169/files#diff-ef32087fbd8a1d30da698a6e6dd04394L34-L36) were the lines that were removed ([hourglass.svg](https://github.com/pulumi/docs/blob/master/static/images/docs/quickstart/hourglass.svg) and [general-architecture.svg](https://github.com/pulumi/docs/blob/master/static/images/docs/quickstart/general-architecture.svg)). Or you may have better ideas.

- [x] (bermudezmt) Add link to install the CLI somewhere more prominently in the Get Started section, for folks who are already familiar with Pulumi and just want the CLI, and don't want to walk through the wizards. (I believe this is now addressed with #1451 as "Download and Install" is now always shown).
- [x] (justinvp) Consider sizing the "choose cloud" icons so they can fit 2 on a row (2x2 grid). Rather than changing the background color on hover, which has inconsistent results based on the cloud provider logo, perhaps add a "slight expand on hover" (kinda like how we differentiate the selected product type on https://app.pulumi.com/site/organizations/add)? Or just make the border size much larger, but keeping the same, white background? **Update**: I'm going to check this off as complete. Christian fixed the background color in #1495. We may still want to rearrange the buttons to a 2x2 grid, but we can consider that as a future improvement.
- [ ] (bermudezmt) P2: Link to API docs throughout the Get Started guides, when referring to particular APIs used in code snippets (S3 bucket, etc.)

**Comment by justinvp** [comment]
Unlikely these will all be addressed this week so moving to the next milestone.

**Comment by lukehoban** [comment]
This is quite old, and we've iterated on this experience quite a lot since the issue was written.  Most still open issues above are either already fixed or tracked elsewhere.
