### ISSUE TITLE
[Epic] Author "the minimum you need to know about language X" guides

### ISSUE THREAD

**Issue by joeduffy** [pulumi/docs#11788]
Right now we assume folks wanting to learn Pulumi understand their language of choice. For many newcomers, however, that's not the right assumption to make.

Let's write a series of user guides that detail the minimum you need to know about language X to be successful with Pulumi. It turns out you can get started with a vast subset -- especially in languages like Python -- and that we should be able to give you a quick 20 minute tour of that subset.

* [ ] https://github.com/pulumi/marketing/issues/328
* [x] https://github.com/pulumi/devrel-team/issues/463
* [ ] C# (maybe other languages (eventually))
* [ ] Go

**Comment by cnunciato** [comment]
Adding Lee's in-progress doc here for reference: https://docs.google.com/document/d/14w1NFUDPxT3qOMEtycMTmq6J6ptJ36r0B9sVCt9wO6A/edit#heading=h.widltx1dim94

> Introduction
> 
> Pulumi uses programming languages you may already have used elsewhere to define infrastructure. Many Pulumi users will have used the languages Pulumi supports to write anything from a quick automation script to fully fledged applications handling millions of users.
> 
> Some users may be coming to Pulumi from other infrastructure as code tools that use configuration languages to define the infrastructure. 
> 
> Whether you’re a language expert of writing your first line in your chosen Pulumi supported language, the following page serves as a great foundation for building amazing Pulumi programs.
> Ecosystem
> Interpreter
> Before you can run any Pulumi programs, you’ll need to make sure you have the interpreter for your language available. Pulumi makes use of this interpreter to build your Pulumi infrastructure, so it needs to be available in your $PATH.
> 
> Many operating systems will have interpreters installed by default but some others may require manual installation. You’ll need to follow the operating system guide for your language of choice.
> 
> Once that’s completed, you’ll need to verify the interpreter is available. Simply run the interpreter to verify it’s working as expected.
> 
> Package Management
> Pulumi uses your language's native package management tool to install Pulumi packages. Those Pulumi packages interface with the cloud provider APIs using a binary which is installed on your machine by the package manager, which Pulumi calls a “plugin”.
> 
> In addition to the plugin, you’ll also get a copy of the SDK related to that plugin, which is a language native package which you’ll interface with directly.
> 
> Each language has different mechanisms for handling package management. They all have their own package management tools, and different ecosystems around how to install those packages. You should at the very least be familiar with the commands listed below, what they do and how they work.
> Types
> Pulumi makes use of the native types in each language to manage and manipulate cloud data. You’ll often see strongly typed Pulumi code to provide a better feedback loop for the author when writing infrastructure code.
> 
> Types vary across our supported languages, but knowing these basic types and how to declare them and use them will help dramatically when defining your infrastructure. This is section is here to help you understand the basic data types, more advanced types will be covered in the data structures section.
> 
> Strings
> Integers
> Booleans
> Data Structures
> All our supported languages handle data structures differently. Each language has its own considerations when handling complex information, and different design goals in mind when allowing you to handle data types.
> 
> The following is not an exhaustive list of the different data types, but is the most common types of data structure you’re likely to encounter when writing Pulumi programs.
> Array-Like
> Complex Mappings
> Control Flow
> Control flow is the ability for you to make decisions in your Pulumi program based on certain conditions. Pulumi is declarative, so your control flow might not be the same as if you were writing an imperative application, but there are still situations where you might want to make decisions inside your code, and still get declarative results.
> Abstractions
> Anything Else
> 

We're picking it up from here and planning on getting at least one of these docs out this quarter (looks like TS to begin with).

**Comment by jkodroff** [comment]
Closing due to inactivity.
