### ISSUE TITLE
GREAT WEBSITE MIGRATION OF 2019

### ISSUE THREAD

**Issue by justinvp** [pulumi/docs#1213]
Rollup of remaining tasks to rollout the combined site. We'll of course have some additional follow-up work afterwards to further deduplicate content, improve the structure & information architecture, etc.

### P1
- [x] [cnunciato] Create `robots.txt`
- [x] [cnunciato] Restore `meta_*` items that were deleted
- [x] [cnunciato] Docs: Search form and results styling
- [x] [cnunciato] Review pricing page (Chris has some feedback)
- [x] [justinvp] Another `pulumi/docs` branch integration from  `master` => `fusion`  (changes since 6/17) (#1220)
- [x] [justinvp] Improve `/docs` page (no longer needs to look like a website “homepage”; add Pulumi intro and diagrams) (#1239)
- [x] [justinvp] Regenerate all API docs (#1227)
- [x] [justinvp] Remove aliases (https://github.com/pulumi/docs/pull/1210)
- [x] [justinvp] Update CLI `gen-markdown` command for new site (https://github.com/pulumi/pulumi/pull/2869)
- [x] [chrsmith] Add latest blog posts (changes since 6/16) (https://github.com/pulumi/docs/pull/1218)
- [x] [chrsmith] Add latest blog posts (changes since 7/1)

### P2
- [x] [cnunciato] Add the "hover menu" for top-level nav items (quick links into the section)
- [x] [cnunciato] Code samples aren’t getting syntax highlighting in www content
- [x] [cnunciato] Mobile experience review / tweaks
- [x] [justinvp] Port change to hide language prologue classes by default (https://github.com/pulumi/docs/pull/1212)
- [x] [justinvp] Nav bar should show which section is active (#1216)

### P3
- [x] [cnunciato] Some heroes still need their background gradients/glows
- [x] [cnunciato] a few places still need those purple-and-gray waves 
- [x] [cnunciato] Some color combinations still aren’t quite right

### P4
- [ ] [justinvp, #1325] Fix styles used on AWS Crosswalk images to use Tailwind
- [ ] [justinvp, #1325] Looks like we have both `/image/pulumi.png` and `/social/pulumi.png` used as meta images. We should standardize on `/image/pulumi.png` and update any [redirects](https://github.com/pulumi/home/pull/507) as appropriate.
- [ ] [cnunciato, #1277] We seem to be generating an `rss.xml` file for all sections; is there a way to make it only generate for `/blog/rss.xml`?

## Rollout

- [x] [justinvp] Deploy redirects for `https://pulumi.io` and `https://blog.pulumi.com` to `https://www.pulumi.com` (adopting existing stack resources as needed) (using https://github.com/pulumi/home/pull/507)
- [x] [chrsmith] Rollout (infrastructure changes, branch changes, etc.)

## Post-Rollout

- [x] [justinvp] Deploy change to service to request `https://www.pulumi.com/latest-version` (avoid unnecessary redirect hop) (https://github.com/pulumi/pulumi-service/pull/3673)
- [ ] [justinvp] Merge change to installer script to request `https://www.pulumi.com/latest-version` (avoid unnecessary redirect hop) (https://github.com/pulumi/get.pulumi.com/pull/43)
- [ ] [justinvp, #1325] Hook up Purgecss to remove unused CSS classes (#1291)
- [x] [praneetloke] Deploy change to `pulumi/pulumi-az-pipelines-task` to request `https://www.pulumi.com/latest-version` (https://github.com/pulumi/pulumi-az-pipelines-task/pull/18)
- [ ] [justinvp, #831] Consider moving `/docs/quickstart/` to the root, e.g. `/get-started` (and decide where we want tutorials to live long term)
- [ ] [chrsmith, #1311] Strip `https://pulumi.io/` prefix from any remaining links (looks like these are actually in our API reference docs; we can fix these up post-rollout)

**Comment by lukehoban** [comment]
- [ ] The whole page "shakes" a bit when navigating between pages - particularly the top nav (which seems to slightly vertically resize during navigation, leading to relayout of everything else on page).

**Comment by praneetloke** [comment]
Carousel on the landing page seems to be missing. I couldn't find a corresponding issue in the main issue description above.

This was on FF (latest version). It's the same on Chrome too.
![Screenshot_2019-06-24 Pulumi](https://user-images.githubusercontent.com/1466314/60034332-48443580-965f-11e9-8088-0c973738d1fe.png)

**Comment by justinvp** [comment]
Do we want to keep the "Announcing Pulumi Crosswalk for AWS" banner on the new site for now?

<img width="1352" alt="Screen Shot 2019-06-24 at 9 09 14 AM" src="https://user-images.githubusercontent.com/710598/60034535-c0126000-965f-11e9-8b10-0cf923357573.png">

**Comment by lukehoban** [comment]
- [ ] Many blog posts have wrong date or title? (wrong date: `blog/program-the-cloud-with-12-pulumi-pearls/`, wrong title: `blog/introducing-pulumi-crosswalk-for-aws-the-easiest-way-to-aws/`)
- [ ] Blog summaries on `/blog/` are missing large parts of the "intro paragraphs" -and instead have giant hero images - makes it hard to get a feel for what content is there.  Relatedly, size of titles relative to  other content on the page feels too small.
- [ ] Blog code blocks have awkward "scroll bars?" even when there is not content to scroll?
- [ ] Blog missing any "related posts" or "recent posts" sidebar - hard to get a feel for what otehr content is available when you are on a post
- [ ] Blog tags feel "strange" - like super granular, and unclear what they mean (`aws/lambda/fargate`?).  Significantly preferred simplicity+clarity of old tags ("AWS", "Serverless", "Kubernetes", "Infrastructure").  Also, was nice that these had counts on them previously so you could quickly get a feel for what kind of other content was available related to topics of interest.

**Comment by joeduffy** [comment]
I'll just keep adding to this over the next 24 hours. Feel free to slurp up any as you see them.

- [ ] Currently selected section tab (e.g. "PRICING") isn't highlighted when navigating to it

**Comment by clstokes** [comment]
Padding is a bit off at this window size.

![image](https://user-images.githubusercontent.com/293763/60362553-15b77700-9996-11e9-91d2-b6d0fbb9a829.png)

**Comment by justinvp** [comment]
The high priority issues have been addressed and the new site is live! Let's consider the remaining follow-ups for next milestone.

**Comment by justinvp** [comment]
Actually, we should just close-out this issue and open a new issue (or issues), but we'll take care of that this week.

**Comment by justinvp** [comment]
Moving this back to M24 and closing since we completed this last milestone. All the remaining feedback is captured in follow-up issues for M25.
