### ISSUE TITLE
Add a note to Command-provider posts to let users know the package is now GA

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#12166]
The following posts contain pre-1.0 code that'll no longer work once 1.0 goes out. We should add notes to the top of these posts (e.g., [like this](https://www.pulumi.com/blog/patterns-drift-detection/)) to let users know where to go for current docs and examples.

```[tasklist]
### Tasks
- [ ] https://www.pulumi.com/blog/top-5-things-for-azure-devs-vm/
- [ ] https://www.pulumi.com/blog/deploying-minecraft-on-azure/
- [ ] https://www.pulumi.com/blog/dynamic-providers/
```

**Comment by thomas11** [comment]
All pre-1.0 code will still work. The `CopyFile` resource is superseded by the new `CopyToRemote` resource, but it will continue to exist in the v1 series of the provider.

**Comment by cnunciato** [comment]
@thomas11 Ah great, thanks! I can see the notice there now as well:

![image](https://github.com/pulumi/docs/assets/274700/c9820232-0240-418c-b6d8-0d55e17f4359)

I'll close this, then.
