### ISSUE TITLE
Crosswalk for Kubernetes

### ISSUE THREAD

**Issue by metral** [pulumi/docs#1870]
Docs & Code - TODOS

Docs: https://github.com/pulumi/docs/tree/crosswalk
Code: https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk

<details open>
<summary>General</summary>

* Docs
  - [ ] Limit codeblocks to ~30 LoC: https://github.com/pulumi/docs/issues/1969
  - [ ] Fix k8s lang chooser bouncing around on click: https://github.com/pulumi/docs/issues/1961
  - [x] Add aliases for old ktpw pages to closely mapped new pages in crosswalk. See [here](https://github.com/pulumi/docs/pull/1864#issuecomment-544527480) for details.
  - [x] Rename all full code header links to point to `master` of ktpw repo instead of the `crosswalk` branch.
  - [x] Fix page sidebar overview - it should only be showing headers for the cloud chosen, not all of the headers on the page: https://github.com/pulumi/docs/issues/1962
  - [x] Work in @spara Feedback PR: https://github.com/pulumi/docs/pull/1964/
  - [x] Add FAQ to Crosswalk index / landing page
  - [x] Update cake diagram on index / landing page (BSTRO is handling this)
  - [x] Address Levi's GCP feedback
  - [x] Move FAQ from bottom of index to its own page to shorten the index page length
  - [x] Add DigitalOcean to FAQ

<details>
<summary>Code</summary>

  - [x] Add readme to each ktpw stack of the necessary config & stack references.
  - [x] Add ktpw readme
  - [x] Sync up all stack config files to be similar
</details>

<details>
<summary>Managed Services:</summary>

* Docs
    * [x] Add push image example to ACR
    * [x] Add push image example to GCR
</details>

<details>
<summary>Control Plane:</summary>

* Docs
    * [x] Refactor AWS YAML & TS code for StorageClasses into k8s-language chooser
    * [x] Azure: Add k8s-language chooser and content for using PVCs like in AWS
    * [x] GCP: Add k8s-language chooser and content for using PVCs like in AWS
</details>

<details>
<summary>Config Defaults:</summary>

* Docs
    * [x] PSP - Add TS & YAML examples for all clouds
</details>

<details>
<summary>Cluster Services:</summary>

* Docs
    * [x] Logging
        * [x] AWS
        * [x] GKE
        * [x] AKS
    * [x] Monitoring
        * [x] AWS
        * [x] GKE
        * [x] AKS
    * [x] Datadog DaemonSet

* Code
    * [x] Logging
        * [x] [AWS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/aws/04-cluster-services)
            * fluentd-cloudwatch
        * [x] [GKE](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/gcp/04-cluster-services)
            * Stack driver
        * [x] [AKS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/azure/04-cluster-services)
            * [Azure Monitor blog post](https://www.pulumi.com/blog/create-aks-clusters-with-monitoring-and-logging-with-pulumi-azure-open-source-sdks/)
    * [x] Monitoring
        * [x] AWS
            * cloudwatch metrics
        * [x] GKE
        * [x] AKS
            * [Azure Monitor blog post](https://www.pulumi.com/blog/create-aks-clusters-with-monitoring-and-logging-with-pulumi-azure-open-source-sdks/)
    * [x] Datadog DaemonSet
</details>

<details>
<summary>App Services</summary>

* Docs
  * [x] Datastores
      * [x] [AWS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/aws/05-app-services) - Postgres RDS & Redis
      * [x] [GKE](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/gcp/05-app-services) - Cloud SQL & Redis
      * [x] [AKS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/azure/05-app-services) - Cosmos DB
  * [x] [General App Services](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/general-app-services)
      * [x] NGINX ingress controller

* Code
  * [x] Datastores
      * [x] [AWS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/aws/05-app-services) - Postgres RDS & Redis
      * [x] [GKE](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/gcp/05-app-services) - Cloud SQL & Redis
      * [x] [AKS](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/azure/05-app-services) - Cosmos DB
  * [x] [General App Services](https://github.com/pulumi/kubernetes-the-prod-way/tree/crosswalk/general-app-services)
      * [x] NGINX ingress controller

</details>

<details>
<summary>Apps - TS</summary>

* Docs (TS)
    * [x] build container, push it to registry, run it as Deployment
    * [x] wordpress with pvc
    * [x] configmap roll out - link to tutorial
    * [x] Deployment with Secret for DB connection info
    * [x] DaemonSet
    * [x] Job
    * [x] Cron Job
    * [x] Stateful Set
    * [x] Sidecar
* Code (TS)
    * [x] build container, push it to registry, run it as Deployment
    * [x] wordpress with pvc
    * [x] Deployment with Secret for DB connection info
    * [x] DaemonSet
    * [x] Job
    * [x] Cron Job
    * [x] Stateful Set
    * [x] Sidecar
</details>

<details>
<summary>Apps - TS KX</summary>

  * [x] build & deploy - AWS
  * [x] build & deploy - Azure
  * [x] build & deploy - GCP
  * [x] Job
  * ~[ ] DaemonSet~
  * ~[ ] CronJob~
  * ~[ ] StatefulSet~
</details

**Comment by metral** [comment]
Closing out with https://github.com/pulumi/docs/pull/1864
