### ISSUE TITLE
Follow-up TODOs for the resource docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2816]
Here's a list of items we've either talked about or gathered from users, specifically on the resource docs. Let's use this issue as a collection bin, then create individual issues to work by as necessary, referring to this one as we go.

### Templates and UI/UX

- [ ] ~Improve the layout and info design of the new index page to better clarify the distinction between resources and APIs, and to make better use of space.~ #2859
- [ ] ~Support anchoring to a property, and within a given language.~ #2854
- [ ] ~Add tooltips for "required" asterisks.~ #2855
- [ ] ~On list pages (e.g., /pkg/aws), add tooltips with explanations of what each module is.~ #2855
- [ ] ~Fill out page titles (`title` tags) more completely.~ #2856
- [ ] ~Clean up `meta` descriptions. (See API docs for comparison.)~ #2856
- [ ] ~Remove pages from the search-exclusion list once we're sure we want to keep the pathing.~ #2856
- [ ] ~Add a logo and tile for Azure AD.~ #2857
- [ ] ~Make examples collapsible, with the first one expanded by default.~ #2858
- [ ] ~Add a “back to top” link to make long pages more usable.~ #2864
- [ ] ~Remove “optional” type identifiers and the like, like the ?s in TS.~ #2863
- [x] For C#, remove the namespace (Pulumi.Input and Pulumi.CustomResourceOptions).
- [ ] ~Show the types in the constructor properties also, for consistency.~ #2865
- [ ] ~Unify the styling between the deprecation notices in the API docs and the Resource docs.~ #2866
- [ ] ~Either link or don't link primitive/built-in types (string, boolean) and do so uniformly across resource and API doc sets.~ #2874
- [ ] ~Indicate the selected language and breadcrumb position persistently, so you know where you are and what you’re looking at.~ #2868
- [ ] ~Add links to the Programming Model docs above inputs and outputs sections~ #2963
- [ ] Split long signatures into multiple lines to reduce the need for horizontal scrolling.

---

### Generator

- [ ] ~Write proper names to the frontmatter for reference in the TOC (e.g., “Google Cloud Platform” vs. “gcp”).~ #2869
- [ ] ~Exclude Input properties from the list of Output properties, and add a message above the Outputs indicating inputs are also outputs.~ #2872
- [ ] ~Group required properties at the top of each section, so they’re more easily recognizable, and keep them internally sorted by alpha.~ #2870
- [ ] ~Remove deprecation notices from comment fields and ensure they're all being written to the DeprecationMessage field.~ #2867
- [x] Support deprecation notices at the resource level.

**Comment by praneetloke** [comment]
I am going to close this since we have separate issues for each of the items.
