### ISSUE TITLE
Fix title tags and meta descriptions in the resource docs

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#2856]
All resource-doc pages (e.g., [here](https://www.pulumi.com/docs/reference/pkg/aws/)) should have:

- [x] more complete page titles (to make them easier to find via search engine)
- [x] trimmed-down meta descriptions for less noisy summary previews: 

![image](https://user-images.githubusercontent.com/274700/78618294-e9872b80-782e-11ea-9e01-82e688102b03.png)

Use the API docs as a guide.

Once this is done, also:

- [x] Remove the  `block_external_search_index` param from these pages.
