### ISSUE TITLE
[Epic] Great Docs

### ISSUE THREAD

**Issue by isaac-pulumi** [pulumi/docs#4578]
## Background
Pulumi has a lot of high-value, high-traffic pages that suffer from high bounce rates. 

There are a number of issues that will need to be solved over time with some thematic changes for each documentation path (e.g. tutorials vs. get-started, vs. intro). For this sprint, the focus will be on high-traffic / high-bounce pages.

The team created a blended score of [page views] * [bounce rate] * [% negative ratings] to create a basis for prioritizing pages for this sprint.  The general theme is that even pages with a high share of negative ratings, there were very few actionable comments.

## General areas for improvement:

- Better overall navigation / UX for the /docs page -- we never explain the difference between get-started, tutorials, examples, intro -- so a summary for each major area might help steer folks to the right information faster.

- Some docs are way too long (programming-model) and/or group concepts that can easily be broken out into separate pages (e.g. configuration and secrets)

- Sub-headings, Table of Contents (right-hand nav) is often inconsistent across similar pages (EKS Crosswalk and GKE tutorial are a good example) - or the headings themselves are unhelpful.

- Most “downvotes” are not accompanied by any comments. We should consider requiring a comment because blind voting isn’t giving us a particularly helpful signal on what needs to be fixed.

## Link to original planning doc
[planning doc](https://docs.google.com/document/d/1WZxTt980KBogFziG_EpNsrLcXH2s6wzK4z3TfGca3pk/edit#)

## Links to Issues for this Epic

- [x] Look into why GCP examples are being lost from docsdocs #4507 
- [ ] /docs UX Improvementsdocs #4579  
- [x] Refactor /docs/intro/concepts/programming-modeldocs #4580 
- [ ] Address high bounce rate on /docs/get-started/azure/docs #4581 
- [x] Address high bounce rate on /docs/get-starteddocs #4582
- [ ] Address user feedback on /docs/intro/concepts/statedocs #4583
- [ ] Add multi-lang examples to /docs/tutorials/aws/ecs-fargate/docs #4584
- [x] Split /docs/intro/concepts/config/ into /config and /secretsdocs #4585  
- [ ] Improve layout for /docs/intro/vs/cloud_template_transpilers/docs #4586
- [ ] Fix Confusing ToC and add an intro to /docs/tutorials/kubernetes/gke/docs #4587
- [ ] Fix user-reported bugs on /docs/guides/crosswalk/aws/eks/docs #4588 
- [x] /docs/intro/vs/terraform/ UX improvmentsdocs #4589 
- [ ] Update /docs/guides/continuous-delivery/github-actions/ when we publish to the GH Marketplacedocs #4590
- [x] Add multi-lang examples to /docs/reference/pkg/aws/ec2/securitygroup/docs #4591

**Comment by lukehoban** [comment]
Closing this out as we are now tracking this work in other places.
