### ISSUE TITLE
[Epic] Replace custom sphinx-based generated Python docs with vanilla sphinx

### ISSUE THREAD

**Issue by lukehoban** [pulumi/docs#4615]
The doc-generator we use for Python-specific API docs, and in particular https://www.pulumi.com/docs/reference/pkg/python/pulumi/, has many issues.

We're going to replace our custom Sphinx-based generator with vanilla Sphinx and one of the built-in themes. That way our docs are in the style of what Python developers expect, similar to our .NET docs.

- [ ] https://github.com/pulumi/pulumi-hugo/issues/434
- [ ] https://github.com/pulumi/docs/issues/7000
- [ ] https://github.com/pulumi/docs/issues/6426

**Comment by komalali** [comment]
We (@davidwrede, @infin8x and I) recently chatted about this when it came up w.r.t Automation API docs. I'd suggest using the [default](https://sphinx-themes.org/sample-sites/default-classic/) or [Read the Docs](https://sphinx-rtd-theme.readthedocs.io/en/stable/) theme and just going with the sphinx autogeneration rather than trying to fit this into our markdown format.

**Comment by komalali** [comment]
I went through the linked issues and noted which ones I expect to be resolved by #4071

**Comment by followben** [comment]
+1 for this. I find [Pulumi's native go docs](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/auto) way easier to navigate than [an unindexed single page for python](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#module-pulumi.automation) which is almost unusable in it's current state. See formatting here for example:
<img width="666" alt="Screen Shot 2021-04-22 at 7 47 07 am" src="https://user-images.githubusercontent.com/23772/115634894-dbc71a00-a34d-11eb-848f-dbc3935a7119.png">

**Comment by jf** [comment]
> +1 for this. For the Automation API I find [Pulumi's native go docs](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/auto) way easier to navigate than [an unindexed single page for python](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#module-pulumi.automation) which is almost unusable in it's current state. See formatting here for example: <img alt="Screen Shot 2021-04-22 at 7 47 07 am" width="666" src="https://user-images.githubusercontent.com/23772/115634894-dbc71a00-a34d-11eb-848f-dbc3935a7119.png">

Indeed. There's tons of this bad formatting (we call it "formatting", but really, information is lost!) everywhere in the doc

**Comment by justinvp** [comment]
I have a WIP branch that switches over to using vanilla sphinx: https://github.com/pulumi/docs/compare/master...justin/python. I think all that's left is rebasing that branch and regenerating, then then opening a PR to get feedback.

Going to try to get this over the line next week as one of my hackathon projects.
