### ISSUE TITLE
[Epic] Better docs search: GA

### ISSUE THREAD

**Issue by susanev** [pulumi/docs#4642]
## overview
current docs search is pretty broken and does not meet users needs. some previous convo around this happened in #1558 and #4213

### examples of user's frustration
- searching for `transformation` gives some results, none of which link you to the resource options which was what the user was looking for
- searching for `tokens` links you to 5 different pages on tokens none with any context around what questions they answer
    ![docs-search-tokens](https://user-images.githubusercontent.com/5489125/100033227-a0c8b680-2dae-11eb-8d72-593eee038606.png)
- trying to search for specific features in the console leads to frustration usually with no relevant results

## features we need in search
- [ ] accurate results
- [ ] typos should not result in limited results
- [ ] search results need context to the information they provide, e.g., is it part of the aws docs?
- [ ] auto-complete, and ability to see results as you type

## tools to research
- [ ] [algolia docs search](https://docsearch.algolia.com/)
- [ ] [swift type](https://swiftype.com/)
- [ ] [elasticsearch](https://www.elastic.co/elasticsearch/)

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/docs/issues/1558 and https://github.com/pulumi/docs/issues/3519 (which possibly should be closed as dupes of this or vice versa?).

**Comment by susanev** [comment]
a recent [community slack mention requesting context in our search results](https://pulumi-community.slack.com/archives/C84L4E3N1/p1607895813304300)

**Comment by tusharshahrs** [comment]
Question:  Is there an equivalent API to Terraform's for searching for an AMI? I found the lookup API, but I can't tell if I can use that to search or if I have to know specifically which AMI to get. Need to find a way to find the built AMI when creating the instances.

This is what they are looking for:
https://www.pulumi.com/docs/reference/pkg/aws/getamiids/ OR
https://www.pulumi.com/docs/reference/pkg/aws/getami/ or


Suggestion for docs: 
One documentation suggestion: include the module in search results. For instance, when I search for "Role" I get 20 results but they all just say "Role". I've been hovering over each result and looking at my browser's status line to figure out which module they're associated with

Here is the [search](https://www.pulumi.com/docs/search/?q=Role)

**Comment by infin8x** [comment]
#### Notes from our sync February 12

@davidwrede dropping these here rather than editing the issue body. We said today in the product/engineering meeting that:

- We want to make sure to launch this work on community slack
- @susanev mentioned making some visual updates to the search bar to draw attention to the improved search

**Comment by susanev** [comment]
wait why is this an epic?

**Comment by infin8x** [comment]
It was originally listed as a top-line item in Luke's doc of Q1 priorities. Are we going to make any noise at all about the new docs search (i.e. do we need to involve marketing)? If not, happy to call this a `tier/0` epic or just an issue.

**Comment by davidwrede** [comment]
@infin8x I just plan on announcing it in the community slack. It's likely those are the users would would care about it the most (i.e. people using Pulumi who have questions about features, concepts, etc.).

**Comment by susanev** [comment]
@infin8x it might be worth mentioning it as part of the site redesign work, but i agree about not having any sort of marketing content when we first release it.

**Comment by susanev** [comment]
i think this will just be on pr though from what i understand

**Comment by davidwrede** [comment]
@susanev Sorta. We've had to merge a few other PRs to test out some changes, but it's just the one big PR that actually switches our site search engine over to Swiftype.

**Comment by infin8x** [comment]
Sounds good! No need to track this as an epic then if you're happy to take care of posting in the community slack when you're done.
