### ISSUE TITLE
Add feedback widget to all docs pages and add feedback button to the doc type nav

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/docs#8981]
## Overview
We'd like to raise the prominence of our feedback functionality in tandem with changes to our Docs & Registry. The changes expand the number of selection from 2 (thumbs up or down) to a scale of 4 reactions. It introduces a feedback widget at the bottom of any hand-authored doc. It also provides access to a feedback dialog via the doc type navigation accessible from every page across docs & registry. 

## Figma preview
<img width="1712" alt="feedback (2)" src="https://user-images.githubusercontent.com/97129308/235035940-2b51dc8c-7bfa-437a-8517-a23c6d916e72.png">

## Changes
- [ ] Replaces thumbs up / thumbs down with a scale of 4 reactions
- [ ] Introduces a widget at the bottom of hand-authored docs
- [ ] Moves GitHub links into the widget (with label and icon changes)
- [ ] Adds a "Feedback" button in the Developer navigation
- [ ] Incorporates reactions into the feedback dialog (minor style changes)
- [ ] Ensure new data maps with old data (e.g. "thumbs up" translates into "useful")

**Comment by thoward** [comment]
@shughes26 does this design work align with your plan for the new CSAT widget? if so, i'll keep it around. if not, i'll close it out since we're moving a different direction.
