### ISSUE TITLE
Ingest and transcribe videos

### ISSUE THREAD

**Issue by cnunciato** [pulumi/docs#9560]
@aaronkao's recent [hackathon](https://github.com/pulumi/docs/pull/9396) [project](https://github.com/pulumi/pulumi-hugo/pull/3123) explored automating the ingestion and transcription of videos from our YouTube channel. We should do the work to get that project over the line and those videos into the right place on pulumi.com. Specific todos below (subject to change as needed, of course). 

```[tasklist]
### Tasks
- [ ] Pull the code over to pulumi/docs
- [ ] Switch the transcription engine to something else (IIRC, we're currently using AWS)
- [ ] Run the code on a schedule to produce pages at SEO-friendly URLS
- [ ] Check those pages into the repo when they change (e.g., when a new video surfaces or when content or metadata changes at the source) 
- [ ] Make the necessary adjustments to the code and/or workflows to ensure we aren't transcribing more often than we need to
```

Current thinking is that this should work much like our examples are ingested today: Run a script on a schedule to look for changes, produce an automated PR when new content lands, and have a human review and merge the PR.

**Comment by thoward** [comment]
Per comment here: https://github.com/pulumi/pulumi-hugo/pull/3123#issuecomment-1779938636 ... we aren't moving forward with this project. 

Checking in @aaronkao . It seems like I should close this as `wont-fix`?
